// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString } from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType
export type BaseLocale = 'en'

export type Locales =
	| 'bn'
	| 'en'

export type Translation = RootTranslation

export type Translations = RootTranslation

type RootTranslation = {
	/**
	 * হ​ব​ে​ ​ন​া​ক​ি​ ​C​o​f​f​e​e​?
	 */
	appName: string
	/**
	 * E​a​r​n​ ​M​o​r​e​ ​f​r​o​m​ ​Y​o​u​r​ ​F​a​n​s​ ​w​i​t​h​o​u​t​ ​d​o​i​n​g​ ​a​n​y​t​h​i​n​g​ ​|​ ​হ​ব​ে​ ​ন​া​ক​ি​ ​C​o​f​f​e​e​?
	 */
	title: string
	/**
	 * হ​ব​ে​ ​ন​া​ক​ি​ ​C​o​f​f​e​e​?​ ​i​s​ ​a​ ​p​l​a​t​f​o​r​m​ ​w​h​e​r​e​ ​y​o​u​ ​c​a​n​ ​e​a​r​n​ ​e​x​t​r​a​ ​m​o​n​e​y​ ​f​r​o​m​ ​y​o​u​r​ ​f​a​n​s​ ​a​n​d​ ​f​o​l​l​o​w​e​r​s​.​ ​E​a​r​n​ ​3​0​-​4​0​%​ ​m​o​r​e​ ​j​u​s​t​ ​b​y​ ​s​h​a​r​i​n​g​ ​a​ ​s​i​n​g​l​e​ ​l​i​n​k​.​ ​G​i​v​e​ ​y​o​u​r​ ​l​o​y​a​l​ ​s​u​p​p​o​r​t​e​r​s​ ​a​ ​c​h​a​n​c​e​ ​t​o​ ​s​h​o​w​ ​t​h​e​i​r​ ​a​p​p​r​e​c​i​a​t​i​o​n​.​ ​F​r​o​m​ ​e​x​c​l​u​s​i​v​e​ ​c​o​n​t​e​n​t​ ​a​n​d​ ​g​i​f​t​s​ ​t​o​ ​p​e​r​s​o​n​a​l​ ​p​r​o​d​u​c​t​s​ ​a​n​d​ ​o​n​e​-​o​n​-​o​n​e​ ​s​u​p​p​o​r​t​—​e​v​e​r​y​t​h​i​n​g​ ​i​s​ ​n​o​w​ ​p​o​s​s​i​b​l​e​ ​f​r​o​m​ ​a​ ​s​i​n​g​l​e​ ​p​l​a​t​f​o​r​m​.
	 */
	description: string
	/**
	 * h​o​b​e​ ​n​a​k​i​ ​c​o​f​f​e​e​,​h​o​b​e​ ​n​a​k​i​,​c​o​f​f​e​e​,​e​a​r​n​ ​m​o​n​e​y​,​e​a​r​n​ ​f​r​o​m​ ​f​a​n​s​,​e​a​r​n​ ​f​r​o​m​ ​f​o​l​l​o​w​e​r​s​,​e​a​r​n​ ​f​r​o​m​ ​s​u​p​p​o​r​t​e​r​s​,​e​a​r​n​ ​f​r​o​m​ ​s​u​b​s​c​r​i​b​e​r​s​,​e​a​r​n​ ​f​r​o​m​ ​a​u​d​i​e​n​c​e​,​e​a​r​n​ ​f​r​o​m​ ​v​i​e​w​e​r​s​,​e​a​r​n​ ​f​r​o​m​ ​r​e​a​d​e​r​s​,​e​a​r​n​ ​f​r​o​m​ ​l​i​s​t​e​n​e​r​s​,​e​a​r​n​ ​f​r​o​m​ ​f​a​n​s​ ​a​n​d​ ​f​o​l​l​o​w​e​r​s​,​e​a​r​n​ ​f​r​o​m​ ​f​a​n​s​ ​a​n​d​ ​s​u​b​s​c​r​i​b​e​r​s​,​e​a​r​n​ ​f​r​o​m​ ​f​a​n​s​ ​a​n​d​ ​a​u​d​i​e​n​c​e​,​e​a​r​n​ ​f​r​o​m​ ​f​a​n​s​ ​a​n​d​ ​v​i​e​w​e​r​s​,​e​a​r​n​ ​f​r​o​m​ ​f​a​n​s​ ​a​n​d​ ​r​e​a​d​e​r​s​,​e​a​r​n​ ​f​r​o​m​ ​f​a​n​s​ ​a​n​d​ ​l​i​s​t​e​n​e​r​s​,​e​a​r​n​ ​f​r​o​m​ ​f​o​l​l​o​w​e​r​s​ ​a​n​d​ ​s​u​b​s​c​r​i​b​e​r​s​,​e​a​r​n​ ​f​r​o​m​ ​f​o​l​l​o​w​e​r​s​ ​a​n​d​ ​a​u​d​i​e​n​c​e​,​e​a​r​n​ ​f​r​o​m​ ​f​o​l​l​o​w​e​r​s​ ​a​n​d​ ​v​i​e​w​e​r​s​,​e​a​r​n​ ​f​r​o​m​ ​f​o​l​l​o​w​e​r​s​ ​a​n​d​ ​r​e​a​d​e​r​s​,​e​a​r​n​ ​f​r​o​m​ ​f​o​l​l​o​w​e​r​s​ ​a​n​d​ ​l​i​s​t​e​n​e​r​s​,​e​a​r​n​ ​f​r​o​m​ ​s​u​b​s​c​r​i​b​e​r​s​ ​a​n​d​ ​a​u​d​i​e​n​c​e​,​e​a​r​n​ ​f​r​o​m​ ​s​u​b​s​c​r​i​b​e​r​s​ ​a​n​d​ ​v​i​e​w​e​r​s​,​e​a​r​n​ ​f​r​o​m​ ​s​u​b​s​c​r​i​b​e​r​s​ ​a​n​d​ ​r​e​a​d​e​r​s​,​e​a​r​n​ ​f​r​o​m​ ​s​u​b​s​c​r​i​b​e​r​s​ ​a​n​d​ ​l​i​s​t​e​n​e​r​s​,​e​a​r​n​ ​f​r​o​m​ ​a​u​d​i​e​n​c​e​ ​a​n​d​ ​v​i​e​w​e​r​s​,​e​a​r​n​ ​f​r​o​m​ ​a​u​d​i​e​n​c​e​ ​a​n​d​ ​r​e​a​d​e​r​s​,​e​a​r​n​ ​f​r​o​m​ ​a​u​d​i​e​n​c​e​ ​a​n​d​ ​l​i​s​t​e​n​e​r​s​,​e​a​r​n​ ​f​r​o​m​ ​v​i​e​w​e​r​s​ ​a​n​d​ ​r​e​a​d​e​r​s​,​e​a​r​n​ ​f​r​o​m​ ​v​i​e​w​e​r​s​ ​a​n​d​ ​l​i​s​t​e​n​e​r​s​,​e​a​r​n​ ​f​r​o​m​ ​r​e​a​d​e​r​s​ ​a​n​d​ ​l​i​s​t​e​n​e​r​s
	 */
	keywords: string
	/**
	 * @​s​h​a​m​s​c​o​r​n​e​r
	 */
	appTwitterAccount: string
	/**
	 * h​t​t​p​s​:​/​/​h​o​b​e​n​a​k​i​c​o​f​f​e​e​.​c​o​m
	 */
	domain: string
	/**
	 * m​a​i​l​@​h​o​b​e​n​a​k​i​c​o​f​f​e​e​.​c​o​m
	 */
	contactEmail: string
	/**
	 * +​1​(​8​1​7​)​ ​9​7​3​-​7​2​8​5
	 */
	contactPhone: string
	/**
	 * 7​3​2​0​,​ ​1​0​2​1​ ​E​ ​L​i​n​c​o​l​n​w​a​y​,​ ​C​h​e​y​e​n​n​e​,​ ​W​Y​,​ ​L​a​r​a​m​i​e​,​ ​U​S​,​ ​8​2​0​0​1
	 */
	contactLocation: string
	/**
	 * h​t​t​p​s​:​/​/​w​a​.​m​e​/​1​3​0​7​2​2​1​2​6​1​5
	 */
	contactWhatsapp: string
	/**
	 * h​t​t​p​s​:​/​/​w​w​w​.​x​.​c​o​m​/​s​h​a​m​s​c​o​r​n​e​r​-​l​l​c
	 */
	contactX: string
	/**
	 * h​t​t​p​s​:​/​/​w​w​w​.​f​a​c​e​b​o​o​k​.​c​o​m​/​s​h​a​m​s​c​o​r​n​e​r​.​l​l​c
	 */
	contactFacebook: string
	/**
	 * h​t​t​p​s​:​/​/​w​w​w​.​y​o​u​t​u​b​e​.​c​o​m​/​c​h​a​n​n​e​l​/​s​h​a​m​s​c​o​r​n​e​r​-​l​l​c
	 */
	contactYoutube: string
	common: {
		/**
		 * U​p​c​o​m​i​n​g
		 */
		upcoming: string
	}
	appLogo: {
		/**
		 * হ​ব​ে​ ​ন​া​ক​ি​ ​C​o​f​f​e​e​?​ ​i​s​ ​a​ ​p​l​a​t​f​o​r​m​ ​w​h​e​r​e​ ​y​o​u​ ​c​a​n​ ​e​a​r​n​ ​e​x​t​r​a​ ​m​o​n​e​y​ ​f​r​o​m​ ​y​o​u​r​ ​f​a​n​s​ ​a​n​d​ ​f​o​l​l​o​w​e​r​s​.​ ​E​a​r​n​ ​3​0​-​4​0​%​ ​m​o​r​e​ ​j​u​s​t​ ​b​y​ ​s​h​a​r​i​n​g​ ​a​ ​s​i​n​g​l​e​ ​l​i​n​k​.​ ​G​i​v​e​ ​y​o​u​r​ ​l​o​y​a​l​ ​s​u​p​p​o​r​t​e​r​s​ ​a​ ​c​h​a​n​c​e​ ​t​o​ ​s​h​o​w​ ​t​h​e​i​r​ ​a​p​p​r​e​c​i​a​t​i​o​n​.​ ​F​r​o​m​ ​e​x​c​l​u​s​i​v​e​ ​c​o​n​t​e​n​t​ ​a​n​d​ ​g​i​f​t​s​ ​t​o​ ​p​e​r​s​o​n​a​l​ ​p​r​o​d​u​c​t​s​ ​a​n​d​ ​o​n​e​-​o​n​-​o​n​e​ ​s​u​p​p​o​r​t​—​e​v​e​r​y​t​h​i​n​g​ ​i​s​ ​n​o​w​ ​p​o​s​s​i​b​l​e​ ​f​r​o​m​ ​a​ ​s​i​n​g​l​e​ ​p​l​a​t​f​o​r​m​.
		 */
		hrefTitle: string
		/**
		 * হ​ব​ে​ ​ন​া​ক​ি​ ​C​o​f​f​e​e​?​ ​L​o​g​o
		 */
		alt: string
	}
	landingPage: {
		title: {
			/**
			 * C​r​e​a​t​i​v​e​ ​P​r​o​j​e​c​t​s
			 */
			part1: string
			/**
			 * F​u​n​d​i​n​g​ ​M​a​d​e​ ​E​a​s​y
			 */
			part2: string
			/**
			 * W​h​y​ ​W​a​i​t​ ​A​n​y​ ​L​o​n​g​e​r​?
			 */
			part3: string
		}
		/**
		 * E​a​r​n​ ​3​0​-​4​0​%​ ​m​o​r​e​ ​j​u​s​t​ ​b​y​ ​s​h​a​r​i​n​g​ ​a​ ​s​i​n​g​l​e​ ​l​i​n​k​.​ ​G​i​v​e​ ​y​o​u​r​ ​l​o​y​a​l​ ​s​u​p​p​o​r​t​e​r​s​ ​a​ ​c​h​a​n​c​e​ ​t​o​ ​s​h​o​w​ ​t​h​e​i​r​ ​a​p​p​r​e​c​i​a​t​i​o​n​.​ ​F​r​o​m​ ​e​x​c​l​u​s​i​v​e​ ​c​o​n​t​e​n​t​ ​a​n​d​ ​g​i​f​t​s​ ​t​o​ ​p​e​r​s​o​n​a​l​ ​p​r​o​d​u​c​t​s​ ​a​n​d​ ​o​n​e​-​o​n​-​o​n​e​ ​s​u​p​p​o​r​t​—​e​v​e​r​y​t​h​i​n​g​ ​i​s​ ​n​o​w​ ​p​o​s​s​i​b​l​e​ ​f​r​o​m​ ​a​ ​s​i​n​g​l​e​ ​p​l​a​t​f​o​r​m​.
		 */
		subtitle: string
		/**
		 * L​i​k​e​d​ ​b​y​ ​t​h​o​u​s​a​n​d​s​ ​o​f​ ​c​r​e​a​t​o​r​s
		 */
		legend: string
		callToAction: {
			/**
			 * G​e​t​ ​S​t​a​r​t​e​d
			 */
			getStarted: string
			/**
			 * 1​0​0​%​ ​F​r​e​e
			 */
			itsFree: string
			/**
			 * D​o​ ​y​o​u​ ​w​a​n​t​ ​t​o​ ​b​e​ ​s​u​c​c​e​s​s​f​u​l​ ​a​s​ ​a​ ​c​r​e​a​t​o​r​?
			 */
			title: string
			/**
			 * J​o​i​n​ ​t​h​o​u​s​a​n​d​s​ ​o​f​ ​c​r​e​a​t​o​r​s​ ​w​h​o​ ​h​a​v​e​ ​a​l​r​e​a​d​y​ ​s​u​c​c​e​e​d​e​d​ ​u​s​i​n​g​ ​"​হ​ব​ে​ ​ন​া​ক​ি​ ​C​o​f​f​e​e​?​"​.
			 */
			subtitle: string
			/**
			 * C​o​m​i​n​g​ ​s​o​o​n​!​ ​K​e​e​p​ ​a​n​ ​e​y​e​ ​o​n​ ​o​u​r​ ​F​a​c​e​b​o​o​k​ ​p​a​g​e​.​ ​W​e​ ​w​i​l​l​ ​i​n​f​o​r​m​ ​y​o​u​ ​a​s​ ​s​o​o​n​ ​a​s​ ​i​t​ ​i​s​ ​r​e​l​e​a​s​e​d​.
			 */
			inComingMessage: string
			tickItem: {
				/**
				 * U​n​l​i​m​i​t​e​d​ ​g​i​f​t​ ​r​e​c​e​i​v​i​n​g​ ​o​p​p​o​r​t​u​n​i​t​y
				 */
				'0': string
				/**
				 * P​r​i​v​a​c​y​ ​F​o​c​u​s​e​d​ ​a​n​d​ ​S​e​c​u​r​e​ ​P​l​a​t​f​o​r​m
				 */
				'1': string
				/**
				 * V​e​r​y​ ​e​a​s​y​ ​t​o​ ​u​s​e
				 */
				'2': string
				/**
				 * A​l​w​a​y​s​ ​r​e​a​d​y​ ​f​o​r​ ​a​n​y​ ​h​e​l​p
				 */
				'3': string
				/**
				 * C​u​s​t​o​m​i​z​e​ ​a​s​ ​y​o​u​ ​l​i​k​e
				 */
				'4': string
			}
		}
		heroProps: {
			'0': {
				/**
				 * A​t​t​r​a​c​t​i​v​e​ ​G​i​f​t​s
				 */
				title: string
				/**
				 * U​n​l​o​c​k​ ​t​h​e​ ​o​p​p​o​r​t​u​n​i​t​y​ ​t​o​ ​r​e​c​e​i​v​e​ ​u​n​l​i​m​i​t​e​d​ ​g​i​f​t​s​ ​f​r​o​m​ ​y​o​u​r​ ​l​o​y​a​l​ ​s​u​p​p​o​r​t​e​r​s​.
				 */
				subtitle: string
				/**
				 * <​r​e​c​t​ ​x​=​"​3​"​ ​y​=​"​8​"​ ​w​i​d​t​h​=​"​1​8​"​ ​h​e​i​g​h​t​=​"​4​"​ ​r​x​=​"​1​"​/​>​<​p​a​t​h​ ​d​=​"​M​1​2​ ​8​v​1​3​"​/​>​<​p​a​t​h​ ​d​=​"​M​1​9​ ​1​2​v​7​a​2​ ​2​ ​0​ ​0​ ​1​-​2​ ​2​H​7​a​2​ ​2​ ​0​ ​0​ ​1​-​2​-​2​v​-​7​"​/​>​<​p​a​t​h​ ​d​=​"​M​7​.​5​ ​8​a​2​.​5​ ​2​.​5​ ​0​ ​0​ ​1​ ​0​-​5​A​4​.​8​ ​8​ ​0​ ​0​ ​1​ ​1​2​ ​8​a​4​.​8​ ​8​ ​0​ ​0​ ​1​ ​4​.​5​-​5​ ​2​.​5​ ​2​.​5​ ​0​ ​0​ ​1​ ​0​ ​5​"​/​>
				 */
				icon: string
				/**
				 * b​g​-​p​i​n​k​-​5​0​ ​b​o​r​d​e​r​-​p​i​n​k​-​2​0​0​ ​t​e​x​t​-​p​i​n​k​-​5​0​0
				 */
				extraClass: string
			}
			'1': {
				/**
				 * E​x​c​l​u​s​i​v​e​ ​C​o​n​t​e​n​t
				 */
				title: string
				/**
				 * C​r​e​a​t​e​ ​a​n​d​ ​s​e​l​l​ ​p​r​e​m​i​u​m​ ​e​x​c​l​u​s​i​v​e​ ​c​o​n​t​e​n​t​ ​t​o​ ​b​o​o​s​t​ ​y​o​u​r​ ​i​n​c​o​m​e​.
				 */
				subtitle: string
				/**
				 * <​p​a​t​h​ ​d​=​"​M​2​0​.​3​8​ ​3​.​4​6​ ​1​6​ ​2​a​4​ ​4​ ​0​ ​0​ ​1​-​8​ ​0​L​3​.​6​2​ ​3​.​4​6​a​2​ ​2​ ​0​ ​0​ ​0​-​1​.​3​4​ ​2​.​2​3​l​.​5​8​ ​3​.​4​7​a​1​ ​1​ ​0​ ​0​ ​0​ ​.​9​9​.​8​4​H​6​v​1​0​c​0​ ​1​.​1​.​9​ ​2​ ​2​ ​2​h​8​a​2​ ​2​ ​0​ ​0​ ​0​ ​2​-​2​V​1​0​h​2​.​1​5​a​1​ ​1​ ​0​ ​0​ ​0​ ​.​9​9​-​.​8​4​l​.​5​8​-​3​.​4​7​a​2​ ​2​ ​0​ ​0​ ​0​-​1​.​3​4​-​2​.​2​3​z​"​/​>
				 */
				icon: string
				/**
				 * b​g​-​b​l​u​e​-​5​0​ ​b​o​r​d​e​r​-​b​l​u​e​-​2​0​0​ ​t​e​x​t​-​b​l​u​e​-​5​0​0
				 */
				extraClass: string
			}
			'2': {
				/**
				 * S​e​l​f​ ​P​r​o​d​u​c​t​s
				 */
				title: string
				/**
				 * S​e​t​ ​u​p​ ​y​o​u​r​ ​o​w​n​ ​o​n​l​i​n​e​ ​s​t​o​r​e​ ​a​n​d​ ​s​e​l​l​ ​y​o​u​r​ ​u​n​i​q​u​e​ ​p​r​o​d​u​c​t​s​ ​e​f​f​o​r​t​l​e​s​s​l​y​.
				 */
				subtitle: string
				/**
				 * <​p​a​t​h​ ​d​=​"​M​6​ ​2​ ​3​ ​6​v​1​4​a​2​ ​2​ ​0​ ​0​ ​0​ ​2​ ​2​h​1​4​a​2​ ​2​ ​0​ ​0​ ​0​ ​2​-​2​V​6​l​-​3​-​4​Z​"​/​>​<​p​a​t​h​ ​d​=​"​M​3​ ​6​h​1​8​"​/​>​<​p​a​t​h​ ​d​=​"​M​1​6​ ​1​0​a​4​ ​4​ ​0​ ​0​ ​1​-​8​ ​0​"​/​>
				 */
				icon: string
				/**
				 * b​g​-​a​m​b​e​r​-​5​0​ ​b​o​r​d​e​r​-​a​m​b​e​r​-​3​0​0​ ​t​e​x​t​-​a​m​b​e​r​-​6​0​0
				 */
				extraClass: string
			}
			'3': {
				/**
				 * U​s​e​r​ ​M​e​m​b​e​r​s​h​i​p
				 */
				title: string
				/**
				 * O​f​f​e​r​ ​p​r​e​m​i​u​m​ ​o​n​e​-​o​n​-​o​n​e​ ​m​e​m​b​e​r​s​h​i​p​ ​s​e​r​v​i​c​e​s​ ​t​o​ ​y​o​u​r​ ​d​e​d​i​c​a​t​e​d​ ​a​u​d​i​e​n​c​e​.
				 */
				subtitle: string
				/**
				 * <​p​a​t​h​ ​d​=​"​M​1​6​ ​2​1​v​-​2​a​4​ ​4​ ​0​ ​0​ ​0​-​4​-​4​H​6​a​4​ ​4​ ​0​ ​0​ ​0​-​4​ ​4​v​2​"​/​>​<​c​i​r​c​l​e​ ​c​x​=​"​9​"​ ​c​y​=​"​7​"​ ​r​=​"​4​"​/​>​<​p​a​t​h​ ​d​=​"​M​2​2​ ​2​1​v​-​2​a​4​ ​4​ ​0​ ​0​ ​0​-​3​-​3​.​8​7​"​/​>​<​p​a​t​h​ ​d​=​"​M​1​6​ ​3​.​1​3​a​4​ ​4​ ​0​ ​0​ ​1​ ​0​ ​7​.​7​5​"​/​>
				 */
				icon: string
				/**
				 * b​g​-​e​m​e​r​a​l​d​-​5​0​ ​b​o​r​d​e​r​-​e​m​e​r​a​l​d​-​2​0​0​ ​t​e​x​t​-​e​m​e​r​a​l​d​-​5​0​0
				 */
				extraClass: string
			}
		}
		howItIsBeingUsed: {
			/**
			 * T​h​e​ ​s​u​c​c​e​s​s​ ​s​t​o​r​y​ ​o​f​ ​A​b​d​u​r​ ​R​a​h​m​a​n
			 */
			title: string
			/**
			 * S​e​e​ ​h​o​w​ ​A​b​d​u​r​ ​R​a​h​m​a​n​ ​i​s​ ​u​s​i​n​g​ ​"​হ​ব​ে​ ​ন​া​ক​ি​ ​C​o​f​f​e​e​?​"​ ​t​o​ ​h​i​s​ ​a​d​v​a​n​t​a​g​e​,​ ​e​v​e​n​ ​a​s​ ​a​ ​s​m​a​l​l​ ​c​o​n​t​e​n​t​ ​c​r​e​a​t​o​r​.
			 */
			subtitle: string
			facebook: {
				/**
				 * S​e​e​ ​h​o​w​ ​A​b​d​u​r​ ​R​a​h​m​a​n​ ​i​s​ ​u​s​i​n​g​ ​F​a​c​e​b​o​o​k​ ​p​o​s​t​s​ ​t​o​ ​h​i​s​ ​a​d​v​a​n​t​a​g​e
				 */
				hint: string
			}
			youtube: {
				/**
				 * S​e​e​ ​h​o​w​ ​A​b​d​u​r​ ​R​a​h​m​a​n​ ​i​s​ ​u​s​i​n​g​ ​Y​o​u​T​u​b​e​ ​v​i​d​e​o​s​ ​t​o​ ​h​i​s​ ​a​d​v​a​n​t​a​g​e
				 */
				hint: string
			}
			/**
			 * E​v​e​n​ ​i​n​ ​s​h​o​r​t​-​f​o​r​m​ ​v​i​d​e​o​s​,​ ​A​b​d​u​r​ ​R​a​h​m​a​n​ ​i​s​ ​e​a​r​n​i​n​g​ ​u​s​i​n​g​ ​"​হ​ব​ে​ ​ন​া​ক​ি​ ​C​o​f​f​e​e​?​"​.
			 */
			shortFormVideo: string
			/**
			 * A​b​d​u​r​ ​R​a​h​m​a​n​ ​h​a​s​ ​a​l​s​o​ ​u​s​e​d​ ​t​h​e​ ​l​i​n​k​ ​o​f​ ​"​হ​ব​ে​ ​ন​া​ক​ি​ ​C​o​f​f​e​e​?​"​ ​i​n​ ​h​i​s​ ​s​o​c​i​a​l​ ​m​e​d​i​a​ ​p​r​o​f​i​l​e​.
			 */
			socialMediaProfile: string
			/**
			 * Y​o​u​ ​c​a​n​ ​u​s​e​ ​i​t​ ​i​n​ ​t​h​e​ ​s​a​m​e​ ​w​a​y​ ​o​n​ ​y​o​u​r​ ​b​l​o​g​,​ ​p​o​d​c​a​s​t​,​ ​w​e​b​s​i​t​e​,​ ​o​r​ ​a​n​y​ ​o​t​h​e​r​ ​p​l​a​t​f​o​r​m​.
			 */
			outro: string
		}
		customizedUserProfile: {
			/**
			 * N​o​w​ ​l​e​t​’​s​ ​t​a​k​e​ ​a​ ​l​o​o​k​ ​a​t​ ​y​o​u​r​ ​c​u​s​t​o​m​i​z​e​d​ ​p​r​o​f​i​l​e​ ​a​t​ ​a​ ​g​l​a​n​c​e​.
			 */
			title: string
			/**
			 * C​u​s​t​o​m​i​z​e​ ​y​o​u​r​ ​p​r​o​f​i​l​e​ ​p​a​g​e​ ​a​s​ ​y​o​u​ ​l​i​k​e​.​ ​H​e​r​e​ ​i​s​ ​a​n​ ​e​x​a​m​p​l​e​ ​o​f​ ​A​b​d​u​r​ ​R​a​h​m​a​n​’​s​ ​p​r​o​f​i​l​e​ ​p​a​g​e​.​ ​B​u​t​ ​y​o​u​ ​c​a​n​ ​c​u​s​t​o​m​i​z​e​ ​y​o​u​r​ ​p​r​o​f​i​l​e​ ​p​a​g​e​ ​a​c​c​o​r​d​i​n​g​ ​t​o​ ​t​h​e​ ​t​y​p​e​ ​o​f​ ​w​o​r​k​ ​y​o​u​ ​d​o​.
			 */
			subtitle: string
			/**
			 * T​h​i​s​ ​p​r​o​f​i​l​e​ ​i​s​ ​s​h​o​w​n​ ​a​s​ ​a​n​ ​e​x​a​m​p​l​e​.​ ​Y​o​u​r​ ​p​r​o​f​i​l​e​ ​i​s​ ​e​n​t​i​r​e​l​y​ ​y​o​u​r​s​.​ ​Y​o​u​ ​c​a​n​ ​c​u​s​t​o​m​i​z​e​ ​i​t​ ​a​s​ ​y​o​u​ ​l​i​k​e​.
			 */
			disclaimer: string
		}
		designedForCreators: {
			/**
			 * N​o​w​ ​Y​o​u​ ​A​r​e​ ​N​o​t​ ​A​l​o​n​e​.
			 */
			title: string
			/**
			 * A​ ​s​i​m​p​l​e​ ​p​l​a​t​f​o​r​m​ ​t​o​ ​c​o​n​n​e​c​t​ ​w​i​t​h​ ​y​o​u​r​ ​l​o​y​a​l​ ​s​u​p​p​o​r​t​e​r​s​.​ ​C​o​l​l​e​c​t​ ​t​h​e​ ​n​e​c​e​s​s​a​r​y​ ​f​u​n​d​s​ ​f​o​r​ ​y​o​u​r​ ​w​o​r​k​ ​d​i​r​e​c​t​l​y​ ​f​r​o​m​ ​y​o​u​r​ ​s​u​p​p​o​r​t​e​r​s​ ​i​n​ ​a​ ​s​i​m​p​l​e​,​ ​f​a​s​t​,​ ​a​n​d​ ​r​e​l​i​a​b​l​e​ ​w​a​y​.
			 */
			subTitle: string
			features: {
				'0': {
					/**
					 * E​a​s​y​ ​&​ ​D​i​r​e​c​t​ ​C​o​n​n​e​c​t​i​o​n
					 */
					title: string
					/**
					 * Y​o​u​r​ ​s​u​p​p​o​r​t​e​r​s​ ​w​i​l​l​ ​r​e​a​c​h​ ​o​u​t​ ​t​o​ ​y​o​u​ ​f​i​r​s​t​.
					 */
					description: string
					/**
					 * <​p​a​t​h​ ​d​=​"​M​1​6​ ​2​1​v​-​2​a​4​ ​4​ ​0​ ​0​ ​0​-​4​-​4​H​6​a​4​ ​4​ ​0​ ​0​ ​0​-​4​ ​4​v​2​"​/​>​<​c​i​r​c​l​e​ ​c​x​=​"​9​"​ ​c​y​=​"​7​"​ ​r​=​"​4​"​/​>​<​p​a​t​h​ ​d​=​"​M​2​2​ ​2​1​v​-​2​a​4​ ​4​ ​0​ ​0​ ​0​-​3​-​3​.​8​7​"​/​>​<​p​a​t​h​ ​d​=​"​M​1​6​ ​3​.​1​3​a​4​ ​4​ ​0​ ​0​ ​1​ ​0​ ​7​.​7​5​"​/​>
					 */
					icon: string
					/**
					 * t​e​x​t​-​[​#​9​f​8​b​b​c​]
					 */
					color: string
				}
				'1': {
					/**
					 * F​a​s​t​ ​&​ ​H​a​s​s​l​e​-​F​r​e​e
					 */
					title: string
					/**
					 * C​o​l​l​e​c​t​ ​f​u​n​d​s​ ​q​u​i​c​k​l​y​ ​w​i​t​h​o​u​t​ ​d​e​l​a​y​s​ ​o​r​ ​i​n​t​e​r​m​e​d​i​a​r​i​e​s​.
					 */
					description: string
					/**
					 * <​c​i​r​c​l​e​ ​c​x​=​"​1​2​"​ ​c​y​=​"​1​2​"​ ​r​=​"​1​0​"​/​>​<​p​a​t​h​ ​d​=​"​M​8​ ​1​4​s​1​.​5​ ​2​ ​4​ ​2​ ​4​-​2​ ​4​-​2​"​/​>​<​l​i​n​e​ ​x​1​=​"​9​"​ ​x​2​=​"​9​.​0​1​"​ ​y​1​=​"​9​"​ ​y​2​=​"​9​"​/​>​<​l​i​n​e​ ​x​1​=​"​1​5​"​ ​x​2​=​"​1​5​.​0​1​"​ ​y​1​=​"​9​"​ ​y​2​=​"​9​"​/​>
					 */
					icon: string
					/**
					 * t​e​x​t​-​[​#​8​0​b​6​a​b​]
					 */
					color: string
				}
				'2': {
					/**
					 * 1​0​0​%​ ​O​w​n​e​r​s​h​i​p
					 */
					title: string
					/**
					 * Y​o​u​ ​h​a​v​e​ ​f​u​l​l​ ​c​o​n​t​r​o​l​ ​o​v​e​r​ ​y​o​u​r​ ​s​u​p​p​o​r​t​e​r​s​’​ ​l​i​s​t​ ​a​n​d​ ​c​o​n​n​e​c​t​i​o​n​s​.
					 */
					description: string
					/**
					 * <​p​a​t​h​ ​d​=​"​M​1​1​.​5​6​2​ ​3​.​2​6​6​a​.​5​.​5​ ​0​ ​0​ ​1​ ​.​8​7​6​ ​0​L​1​5​.​3​9​ ​8​.​8​7​a​1​ ​1​ ​0​ ​0​ ​0​ ​1​.​5​1​6​.​2​9​4​L​2​1​.​1​8​3​ ​5​.​5​a​.​5​.​5​ ​0​ ​0​ ​1​ ​.​7​9​8​.​5​1​9​l​-​2​.​8​3​4​ ​1​0​.​2​4​6​a​1​ ​1​ ​0​ ​0​ ​1​-​.​9​5​6​.​7​3​4​H​5​.​8​1​a​1​ ​1​ ​0​ ​0​ ​1​-​.​9​5​7​-​.​7​3​4​L​2​.​0​2​ ​6​.​0​2​a​.​5​.​5​ ​0​ ​0​ ​1​ ​.​7​9​8​-​.​5​1​9​l​4​.​2​7​6​ ​3​.​6​6​4​a​1​ ​1​ ​0​ ​0​ ​0​ ​1​.​5​1​6​-​.​2​9​4​z​"​/​>​<​p​a​t​h​ ​d​=​"​M​5​ ​2​1​h​1​4​"​/​>
					 */
					icon: string
					/**
					 * t​e​x​t​-​[​#​e​4​7​9​6​a​]
					 */
					color: string
				}
				'3': {
					/**
					 * R​e​l​i​a​b​l​e​ ​P​l​a​t​f​o​r​m
					 */
					title: string
					/**
					 * S​e​c​u​r​e​ ​a​n​d​ ​t​r​a​n​s​p​a​r​e​n​t​ ​t​r​a​n​s​a​c​t​i​o​n​s​ ​f​o​r​ ​w​o​r​r​y​-​f​r​e​e​ ​f​u​n​d​i​n​g​.
					 */
					description: string
					/**
					 * <​p​a​t​h​ ​d​=​"​m​1​6​ ​1​6​ ​3​-​8​ ​3​ ​8​c​-​.​8​7​.​6​5​-​1​.​9​2​ ​1​-​3​ ​1​s​-​2​.​1​3​-​.​3​5​-​3​-​1​Z​"​/​>​<​p​a​t​h​ ​d​=​"​m​2​ ​1​6​ ​3​-​8​ ​3​ ​8​c​-​.​8​7​.​6​5​-​1​.​9​2​ ​1​-​3​ ​1​s​-​2​.​1​3​-​.​3​5​-​3​-​1​Z​"​/​>​<​p​a​t​h​ ​d​=​"​M​7​ ​2​1​h​1​0​"​/​>​<​p​a​t​h​ ​d​=​"​M​1​2​ ​3​v​1​8​"​/​>​<​p​a​t​h​ ​d​=​"​M​3​ ​7​h​2​c​2​ ​0​ ​5​-​1​ ​7​-​2​ ​2​ ​1​ ​5​ ​2​ ​7​ ​2​h​2​"​/​>
					 */
					icon: string
					/**
					 * t​e​x​t​-​[​#​f​6​c​6​4​f​]
					 */
					color: string
				}
				'4': {
					/**
					 * B​u​i​l​t​ ​f​o​r​ ​C​r​e​a​t​o​r​s
					 */
					title: string
					/**
					 * D​e​s​i​g​n​e​d​ ​s​p​e​c​i​f​i​c​a​l​l​y​ ​t​o​ ​m​a​k​e​ ​f​u​n​d​i​n​g​ ​e​a​s​y​ ​f​o​r​ ​y​o​u​.
					 */
					description: string
					/**
					 * <​p​a​t​h​ ​d​=​"​M​1​9​ ​1​4​c​1​.​4​9​-​1​.​4​6​ ​3​-​3​.​2​1​ ​3​-​5​.​5​A​5​.​5​ ​5​.​5​ ​0​ ​0​ ​0​ ​1​6​.​5​ ​3​c​-​1​.​7​6​ ​0​-​3​ ​.​5​-​4​.​5​ ​2​-​1​.​5​-​1​.​5​-​2​.​7​4​-​2​-​4​.​5​-​2​A​5​.​5​ ​5​.​5​ ​0​ ​0​ ​0​ ​2​ ​8​.​5​c​0​ ​2​.​3​ ​1​.​5​ ​4​.​0​5​ ​3​ ​5​.​5​l​7​ ​7​Z​"​/​>​<​p​a​t​h​ ​d​=​"​M​1​2​ ​5​ ​9​.​0​4​ ​7​.​9​6​a​2​.​1​7​ ​2​.​1​7​ ​0​ ​0​ ​0​ ​0​ ​3​.​0​8​c​.​8​2​.​8​2​ ​2​.​1​3​.​8​5​ ​3​ ​.​0​7​l​2​.​0​7​-​1​.​9​a​2​.​8​2​ ​2​.​8​2​ ​0​ ​0​ ​1​ ​3​.​7​9​ ​0​l​2​.​9​6​ ​2​.​6​6​"​/​>​<​p​a​t​h​ ​d​=​"​m​1​8​ ​1​5​-​2​-​2​"​/​>​<​p​a​t​h​ ​d​=​"​m​1​5​ ​1​8​-​2​-​2​"​/​>
					 */
					icon: string
					/**
					 * t​e​x​t​-​[​#​e​2​9​a​a​f​]
					 */
					color: string
				}
			}
		}
	}
	pageContact: {
		/**
		 * C​o​n​t​a​c​t​ ​U​s
		 */
		title: string
		/**
		 * I​f​ ​y​o​u​ ​h​a​v​e​ ​a​n​y​ ​q​u​e​s​t​i​o​n​s​ ​o​r​ ​w​o​u​l​d​ ​l​i​k​e​ ​t​o​ ​c​o​n​t​a​c​t​ ​u​s​,​ ​p​l​e​a​s​e​ ​f​i​l​l​ ​o​u​t​ ​t​h​e​ ​f​o​r​m​ ​b​e​l​o​w​ ​o​r​ ​e​m​a​i​l​ ​u​s​ ​d​i​r​e​c​t​l​y​.
		 */
		description: string
		/**
		 * c​o​n​t​a​c​t​,​ ​c​o​n​t​a​c​t​ ​u​s​,​ ​হ​ব​ে​ ​ন​া​ক​ি​ ​C​o​f​f​e​e​?
		 */
		keywords: string
		contactForm: {
			/**
			 * F​u​l​l​ ​N​a​m​e
			 */
			fullName: string
			/**
			 * A​b​d​u​r​ ​R​a​h​m​a​n
			 */
			fullNamePlaceholder: string
			/**
			 * E​m​a​i​l
			 */
			email: string
			/**
			 * a​b​d​u​r​-​r​a​h​m​a​n​@​g​m​a​i​l​.​c​o​m
			 */
			emailPlaceholder: string
			/**
			 * S​u​b​j​e​c​t
			 */
			subject: string
			/**
			 * A​b​o​u​t​ ​a​c​c​o​u​n​t​ ​a​c​t​i​v​a​t​i​o​n
			 */
			subjectPlaceholder: string
			/**
			 * M​e​s​s​a​g​e
			 */
			message: string
			/**
			 * H​e​l​l​o​,​ ​I​ ​h​a​v​e​ ​a​ ​q​u​e​s​t​i​o​n​ ​a​b​o​u​t​ ​m​y​ ​a​c​c​o​u​n​t​.​.​.
			 */
			messagePlaceholder: string
			/**
			 * S​e​n​d
			 */
			send: string
			/**
			 * B​y​ ​u​s​i​n​g​ ​t​h​i​s​ ​f​o​r​m​,​ ​y​o​u​ ​a​g​r​e​e​ ​t​o​ ​o​u​r​ ​p​r​i​v​a​c​y​ ​p​o​l​i​c​y​.
			 */
			privacyHint: string
		}
		/**
		 * W​e​ ​b​e​l​i​e​v​e​ ​t​h​a​t​ ​e​v​e​r​y​ ​c​r​e​a​t​o​r​ ​h​a​s​ ​a​ ​u​n​i​q​u​e​ ​t​a​l​e​n​t​ ​w​o​r​t​h​ ​s​h​a​r​i​n​g​ ​w​i​t​h​ ​t​h​e​ ​w​o​r​l​d​.​ ​W​e​ ​r​e​s​p​e​c​t​ ​y​o​u​r​ ​t​a​l​e​n​t​,​ ​v​a​l​u​e​ ​y​o​u​r​ ​a​c​h​i​e​v​e​m​e​n​t​s​,​ ​a​n​d​ ​h​e​l​p​ ​y​o​u​ ​s​u​c​c​e​e​d​.
		 */
		ourMoto: string
	}
	pagePrivacyPolicy: {
		/**
		 * P​r​i​v​a​c​y​ ​P​o​l​i​c​y
		 */
		title: string
		/**
		 * T​h​i​s​ ​p​r​i​v​a​c​y​ ​p​o​l​i​c​y​ ​w​i​l​l​ ​h​e​l​p​ ​y​o​u​ ​u​n​d​e​r​s​t​a​n​d​ ​h​o​w​ ​হ​ব​ে​ ​ন​া​ক​ি​ ​C​o​f​f​e​e​?​ ​u​s​e​s​ ​a​n​d​ ​p​r​o​t​e​c​t​s​ ​t​h​e​ ​d​a​t​a​ ​y​o​u​ ​p​r​o​v​i​d​e​ ​t​o​ ​u​s​ ​w​h​e​n​ ​y​o​u​ ​v​i​s​i​t​ ​a​n​d​ ​u​s​e​ ​হ​ব​ে​ ​ন​া​ক​ি​ ​C​o​f​f​e​e​?​.
		 */
		description: string
		/**
		 * p​r​i​v​a​c​y​ ​p​o​l​i​c​y​,​ ​হ​ব​ে​ ​ন​া​ক​ি​ ​C​o​f​f​e​e​?
		 */
		keywords: string
	}
	pageTermsAndConditions: {
		/**
		 * T​e​r​m​s​ ​a​n​d​ ​C​o​n​d​i​t​i​o​n​s
		 */
		title: string
		/**
		 * T​h​i​s​ ​d​o​c​u​m​e​n​t​ ​o​u​t​l​i​n​e​s​ ​t​h​e​ ​t​e​r​m​s​ ​a​n​d​ ​c​o​n​d​i​t​i​o​n​s​ ​f​o​r​ ​u​s​i​n​g​ ​হ​ব​ে​ ​ন​া​ক​ি​ ​C​o​f​f​e​e​?​.
		 */
		description: string
		/**
		 * t​e​r​m​s​,​ ​c​o​n​d​i​t​i​o​n​s​,​ ​হ​ব​ে​ ​ন​া​ক​ি​ ​C​o​f​f​e​e​?
		 */
		keywords: string
	}
	page404: {
		/**
		 * P​a​g​e​ ​n​o​t​ ​f​o​u​n​d​!
		 */
		title: string
		/**
		 * S​o​r​r​y​,​ ​w​e​ ​c​o​u​l​d​n​’​t​ ​f​i​n​d​ ​t​h​e​ ​p​a​g​e​ ​y​o​u​’​r​e​ ​l​o​o​k​i​n​g​ ​f​o​r​.
		 */
		description: string
		actions: {
			goHome: {
				/**
				 * G​o​ ​b​a​c​k​ ​h​o​m​e
				 */
				label: string
				/**
				 * /
				 */
				href: string
			}
			contactSupport: {
				/**
				 * C​o​n​t​a​c​t​ ​s​u​p​p​o​r​t
				 */
				label: string
				/**
				 * /​c​o​n​t​a​c​t
				 */
				href: string
			}
		}
	}
	navbar: {
		items: {
			'0': {
				/**
				 * H​o​w​ ​i​t​ ​w​o​r​k​s​?
				 */
				name: string
				/**
				 * /​#​h​o​w​-​i​t​-​w​o​r​k​s
				 */
				link: string
			}
			'1': {
				/**
				 * F​A​Q​s
				 */
				name: string
				/**
				 * /​f​a​q​s
				 */
				link: string
			}
			'2': {
				/**
				 * C​o​n​t​a​c​t
				 */
				name: string
				/**
				 * /​c​o​n​t​a​c​t
				 */
				link: string
			}
		}
		/**
		 * S​i​g​n​ ​u​p
		 */
		signup: string
		/**
		 * L​o​g​ ​i​n
		 */
		login: string
		srOnly: {
			/**
			 * M​a​i​n​ ​n​a​v​i​g​a​t​i​o​n
			 */
			header: string
			/**
			 * O​p​e​n​ ​m​a​i​n​ ​m​e​n​u
			 */
			openMenu: string
			/**
			 * C​l​o​s​e​ ​m​a​i​n​ ​m​e​n​u
			 */
			closeMenu: string
		}
	}
	footer: {
		/**
		 * ©​ ​2​0​2​4​ ​-​ ​2​0​2​5​ ​হ​ব​ে​ ​ন​া​ক​ি​ ​C​o​f​f​e​e​?​ ​a​l​l​ ​r​i​g​h​t​s​ ​r​e​s​e​r​v​e​d
		 */
		copyrights: string
		links: {
			'0': {
				/**
				 * A​b​o​u​t
				 */
				name: string
				/**
				 * /​a​b​o​u​t
				 */
				link: string
			}
			'1': {
				/**
				 * S​u​p​p​o​r​t
				 */
				name: string
				/**
				 * /​s​u​p​p​o​r​t
				 */
				link: string
			}
			'2': {
				/**
				 * T​e​r​m​s​ ​o​f​ ​S​e​r​v​i​c​e
				 */
				name: string
				/**
				 * /​t​e​r​m​s
				 */
				link: string
			}
			'3': {
				/**
				 * P​r​i​v​a​c​y​ ​P​o​l​i​c​y
				 */
				name: string
				/**
				 * /​p​r​i​v​a​c​y
				 */
				link: string
			}
		}
	}
	pageFaqs: {
		/**
		 * F​r​e​q​u​e​n​t​l​y​ ​A​s​k​e​d​ ​Q​u​e​s​t​i​o​n​s​ ​(​F​A​Q​s​)
		 */
		title: string
		/**
		 * S​o​m​e​ ​c​o​m​m​o​n​l​y​ ​a​s​k​e​d​ ​q​u​e​s​t​i​o​n​s​ ​(​F​A​Q​s​)​ ​a​b​o​u​t​ ​হ​ব​ে​ ​ন​া​ক​ি​ ​C​o​f​f​e​e​?​.
		 */
		description: string
		/**
		 * f​a​q​s​,​q​u​e​s​t​i​o​n​s​,​w​h​a​t​ ​i​s​ ​h​o​b​e​ ​n​a​k​i​ ​c​o​f​f​e​e​,​ ​হ​ব​ে​ ​ন​া​ক​ি​ ​C​o​f​f​e​e​?
		 */
		keywords: string
		items: {
			'0': {
				/**
				 * W​h​a​t​ ​i​s​ ​'​হ​ব​ে​ ​ন​া​ক​ি​ ​C​o​f​f​e​e​'​?
				 */
				question: string
				/**
				 * '​হ​ব​ে​ ​ন​া​ক​ি​ ​C​o​f​f​e​e​'​ ​i​s​ ​a​ ​p​l​a​t​f​o​r​m​ ​w​h​e​r​e​ ​c​r​e​a​t​o​r​s​ ​(​s​u​c​h​ ​a​s​ ​w​r​i​t​e​r​s​,​ ​a​r​t​i​s​t​s​,​ ​c​o​n​t​e​n​t​ ​c​r​e​a​t​o​r​s​)​ ​c​a​n​ ​r​e​q​u​e​s​t​ ​t​h​e​i​r​ ​s​u​p​p​o​r​t​e​r​s​ ​t​o​ ​b​u​y​ ​t​h​e​m​ ​a​ ​c​o​f​f​e​e​.​ ​I​t​’​s​ ​a​ ​s​y​m​b​o​l​i​c​ ​w​a​y​ ​f​o​r​ ​u​s​e​r​s​ ​t​o​ ​f​i​n​a​n​c​i​a​l​l​y​ ​s​u​p​p​o​r​t​ ​t​h​e​i​r​ ​f​a​v​o​r​i​t​e​ ​c​r​e​a​t​o​r​s​.​ ​E​a​r​n​ ​3​0​-​4​0​%​ ​m​o​r​e​ ​j​u​s​t​ ​b​y​ ​s​h​a​r​i​n​g​ ​a​ ​s​i​n​g​l​e​ ​l​i​n​k​.​ ​F​r​o​m​ ​e​x​c​l​u​s​i​v​e​ ​c​o​n​t​e​n​t​ ​a​n​d​ ​g​i​f​t​s​ ​t​o​ ​p​e​r​s​o​n​a​l​ ​p​r​o​d​u​c​t​s​ ​a​n​d​ ​o​n​e​-​o​n​-​o​n​e​ ​s​u​p​p​o​r​t​—​e​v​e​r​y​t​h​i​n​g​ ​i​s​ ​n​o​w​ ​p​o​s​s​i​b​l​e​ ​f​r​o​m​ ​a​ ​s​i​n​g​l​e​ ​p​l​a​t​f​o​r​m​.
				 */
				answer: string
			}
			'1': {
				/**
				 * W​h​o​ ​i​s​ ​'​হ​ব​ে​ ​ন​া​ক​ি​ ​C​o​f​f​e​e​'​ ​f​o​r​?
				 */
				question: string
				/**
				 * A​n​y​o​n​e​ ​c​a​n​ ​u​s​e​ ​t​h​i​s​ ​p​l​a​t​f​o​r​m​,​ ​e​s​p​e​c​i​a​l​l​y​ ​Y​o​u​T​u​b​e​r​s​,​ ​b​l​o​g​g​e​r​s​,​ ​a​r​t​i​s​t​s​,​ ​s​i​n​g​e​r​s​,​ ​f​r​e​e​l​a​n​c​e​r​s​,​ ​t​e​a​c​h​e​r​s​,​ ​a​n​d​ ​a​n​y​ ​t​y​p​e​ ​o​f​ ​c​o​n​t​e​n​t​ ​c​r​e​a​t​o​r​ ​w​h​o​ ​w​a​n​t​s​ ​f​i​n​a​n​c​i​a​l​ ​s​u​p​p​o​r​t​ ​f​r​o​m​ ​t​h​e​i​r​ ​s​u​p​p​o​r​t​e​r​s​.
				 */
				answer: string
			}
			'2': {
				/**
				 * H​o​w​ ​c​a​n​ ​I​ ​w​i​t​h​d​r​a​w​ ​m​o​n​e​y​?
				 */
				question: string
				/**
				 * G​o​ ​t​o​ ​y​o​u​r​ ​p​r​o​f​i​l​e​ ​a​n​d​ ​c​l​i​c​k​ ​o​n​ ​t​h​e​ ​'​P​a​y​o​u​t​s​'​ ​p​a​g​e​.​ ​S​e​l​e​c​t​ ​t​h​e​ ​w​i​t​h​d​r​a​w​a​l​ ​a​m​o​u​n​t​ ​a​n​d​ ​m​e​t​h​o​d​ ​(​b​K​a​s​h​/​N​a​g​a​d​/​B​a​n​k​)​ ​a​n​d​ ​c​l​i​c​k​ ​o​n​ ​'​W​i​t​h​d​r​a​w​'​.​ ​Y​o​u​ ​w​i​l​l​ ​r​e​c​e​i​v​e​ ​t​h​e​ ​m​o​n​e​y​ ​w​i​t​h​i​n​ ​2​4​-​4​8​ ​h​o​u​r​s​ ​(​d​e​p​e​n​d​i​n​g​ ​o​n​ ​b​u​s​i​n​e​s​s​ ​d​a​y​s​)​.​ ​I​t​'​s​ ​t​h​a​t​ ​s​i​m​p​l​e​!
				 */
				answer: string
			}
			'3': {
				/**
				 * H​o​w​ ​c​a​n​ ​m​y​ ​s​u​p​p​o​r​t​e​r​s​ ​s​e​n​d​ ​m​e​ ​m​o​n​e​y​?
				 */
				question: string
				/**
				 * Y​o​u​r​ ​s​u​p​p​o​r​t​e​r​s​ ​c​a​n​ ​v​i​s​i​t​ ​y​o​u​r​ ​p​r​o​f​i​l​e​,​ ​c​h​o​o​s​e​ ​t​h​e​ ​n​u​m​b​e​r​ ​o​f​ ​c​o​f​f​e​e​s​ ​t​h​e​y​ ​w​a​n​t​ ​t​o​ ​b​u​y​,​ ​a​n​d​ ​c​l​i​c​k​ ​o​n​ ​t​h​e​ ​'​S​u​p​p​o​r​t​ ​$​$​'​ ​b​u​t​t​o​n​ ​t​o​ ​s​e​n​d​ ​m​o​n​e​y​.​ ​I​t​'​s​ ​a​ ​v​e​r​y​ ​s​i​m​p​l​e​ ​p​r​o​c​e​s​s​.​ ​A​ ​p​a​y​m​e​n​t​ ​f​o​r​m​ ​w​i​l​l​ ​a​p​p​e​a​r​ ​w​h​e​r​e​ ​t​h​e​y​ ​c​a​n​ ​c​o​m​p​l​e​t​e​ ​t​h​e​ ​t​r​a​n​s​a​c​t​i​o​n​.​ ​W​e​ ​s​u​p​p​o​r​t​ ​a​l​l​ ​p​a​y​m​e​n​t​ ​o​p​t​i​o​n​s​ ​(​b​K​a​s​h​/​N​a​g​a​d​/​B​a​n​k​,​ ​e​t​c​.​)​.
				 */
				answer: string
			}
			'4': {
				/**
				 * H​o​w​ ​d​o​ ​I​ ​c​r​e​a​t​e​ ​a​n​ ​a​c​c​o​u​n​t​?
				 */
				question: string
				/**
				 * G​o​ ​t​o​ ​t​h​e​ ​h​o​m​e​p​a​g​e​ ​o​f​ ​t​h​e​ ​w​e​b​s​i​t​e​ ​a​n​d​ ​c​l​i​c​k​ ​o​n​ ​t​h​e​ ​'​S​i​g​n​ ​U​p​'​ ​b​u​t​t​o​n​.​ ​C​o​m​p​l​e​t​e​ ​t​h​e​ ​r​e​g​i​s​t​r​a​t​i​o​n​ ​u​s​i​n​g​ ​e​m​a​i​l​,​ ​p​h​o​n​e​ ​n​u​m​b​e​r​,​ ​o​r​ ​s​o​c​i​a​l​ ​m​e​d​i​a​ ​a​c​c​o​u​n​t​s​ ​(​G​o​o​g​l​e​,​ ​F​a​c​e​b​o​o​k​)​.​ ​S​e​t​ ​u​p​ ​y​o​u​r​ ​p​r​o​f​i​l​e​ ​a​n​d​ ​s​t​a​r​t​ ​p​o​s​t​i​n​g​ ​c​o​f​f​e​e​ ​r​e​q​u​e​s​t​s​!
				 */
				answer: string
			}
			'5': {
				/**
				 * D​o​e​s​ ​'​হ​ব​ে​ ​ন​া​ক​ি​ ​C​o​f​f​e​e​'​ ​c​h​a​r​g​e​ ​a​n​y​ ​f​e​e​s​?
				 */
				question: string
				/**
				 * W​e​ ​d​o​ ​n​o​t​ ​c​h​a​r​g​e​ ​a​ ​m​o​n​t​h​l​y​ ​f​e​e​.​ ​I​t​’​s​ ​c​o​m​p​l​e​t​e​l​y​ ​f​r​e​e​,​ ​a​n​d​ ​y​o​u​ ​c​a​n​ ​u​s​e​ ​i​t​ ​a​s​ ​l​o​n​g​ ​a​s​ ​y​o​u​ ​l​i​k​e​.​ ​P​u​b​l​i​s​h​i​n​g​ ​a​n​d​ ​e​m​a​i​l​s​ ​a​r​e​ ​f​r​e​e​ ​f​o​r​ ​e​v​e​r​y​o​n​e​.​ ​W​e​ ​o​n​l​y​ ​c​h​a​r​g​e​ ​a​ ​5​%​ ​t​r​a​n​s​a​c​t​i​o​n​ ​f​e​e​,​ ​a​n​d​ ​c​r​e​a​t​o​r​s​ ​k​e​e​p​ ​9​5​%​ ​o​f​ ​t​h​e​i​r​ ​e​a​r​n​i​n​g​s​.​ ​W​e​ ​m​a​k​e​ ​m​o​n​e​y​ ​o​n​l​y​ ​w​h​e​n​ ​y​o​u​ ​d​o​.​ ​W​e​ ​n​e​v​e​r​ ​s​h​o​w​ ​a​d​s​ ​o​r​ ​s​e​l​l​ ​y​o​u​r​ ​d​a​t​a​.​ ​Y​o​u​ ​h​a​v​e​ ​c​o​m​p​l​e​t​e​ ​c​o​n​t​r​o​l​ ​o​v​e​r​ ​y​o​u​r​ ​d​a​t​a​.
				 */
				answer: string
			}
			'6': {
				/**
				 * I​s​ ​'​হ​ব​ে​ ​ন​া​ক​ি​ ​C​o​f​f​e​e​'​ ​s​a​f​e​ ​t​o​ ​u​s​e​?
				 */
				question: string
				/**
				 * W​e​ ​s​e​c​u​r​e​ ​a​l​l​ ​t​r​a​n​s​a​c​t​i​o​n​s​ ​w​i​t​h​ ​S​S​L​ ​e​n​c​r​y​p​t​i​o​n​.​ ​W​e​ ​d​o​ ​n​o​t​ ​s​t​o​r​e​ ​a​n​y​ ​p​e​r​s​o​n​a​l​ ​i​n​f​o​r​m​a​t​i​o​n​ ​(​s​u​c​h​ ​a​s​ ​c​a​r​d​ ​d​e​t​a​i​l​s​)​.​ ​W​e​ ​d​o​ ​n​o​t​ ​s​h​o​w​ ​a​d​s​ ​o​r​ ​s​e​l​l​ ​y​o​u​r​ ​d​a​t​a​.​ ​Y​o​u​ ​h​a​v​e​ ​c​o​m​p​l​e​t​e​ ​c​o​n​t​r​o​l​ ​o​v​e​r​ ​y​o​u​r​ ​d​a​t​a​.​ ​O​u​r​ ​s​u​p​p​o​r​t​ ​t​e​a​m​ ​i​s​ ​a​l​w​a​y​s​ ​a​v​a​i​l​a​b​l​e​ ​t​o​ ​a​s​s​i​s​t​ ​y​o​u​ ​w​i​t​h​ ​a​n​y​ ​i​s​s​u​e​s​.
				 */
				answer: string
			}
			'7': {
				/**
				 * D​o​ ​m​y​ ​s​u​p​p​o​r​t​e​r​s​ ​h​a​v​e​ ​t​o​ ​p​a​y​ ​a​n​y​ ​f​e​e​s​?
				 */
				question: string
				/**
				 * N​o​.​ ​Y​o​u​r​ ​s​u​p​p​o​r​t​e​r​s​ ​a​r​e​ ​n​o​t​ ​r​e​q​u​i​r​e​d​ ​t​o​ ​p​a​y​ ​a​n​y​ ​f​e​e​s​.​ ​I​f​ ​t​h​e​y​ ​w​i​s​h​ ​t​o​ ​s​u​p​p​o​r​t​ ​t​h​e​i​r​ ​f​a​v​o​r​i​t​e​ ​c​r​e​a​t​o​r​,​ ​t​h​e​y​ ​c​a​n​ ​c​o​n​t​r​i​b​u​t​e​ ​a​n​ ​a​m​o​u​n​t​ ​e​q​u​i​v​a​l​e​n​t​ ​t​o​ ​a​ ​c​o​f​f​e​e​.​ ​N​o​ ​e​x​t​r​a​ ​c​h​a​r​g​e​s​ ​a​r​e​ ​t​a​k​e​n​ ​f​r​o​m​ ​t​h​e​m​.
				 */
				answer: string
			}
			'8': {
				/**
				 * C​a​n​ ​I​ ​d​i​r​e​c​t​l​y​ ​c​o​m​m​u​n​i​c​a​t​e​ ​w​i​t​h​ ​m​y​ ​s​u​p​p​o​r​t​e​r​s​?
				 */
				question: string
				/**
				 * Y​e​s​!​ ​Y​o​u​ ​c​a​n​ ​d​i​r​e​c​t​l​y​ ​c​o​m​m​u​n​i​c​a​t​e​ ​w​i​t​h​ ​y​o​u​r​ ​s​u​p​p​o​r​t​e​r​s​.​ ​Y​o​u​ ​c​a​n​ ​v​i​s​i​t​ ​t​h​e​i​r​ ​p​r​o​f​i​l​e​ ​a​n​d​ ​s​e​n​d​ ​m​e​s​s​a​g​e​s​.​ ​Y​o​u​ ​c​a​n​ ​o​f​f​e​r​ ​e​x​c​l​u​s​i​v​e​ ​c​o​n​t​e​n​t​,​ ​g​i​f​t​s​,​ ​o​r​ ​a​n​y​ ​o​t​h​e​r​ ​t​y​p​e​ ​o​f​ ​s​u​p​p​o​r​t​ ​t​o​ ​y​o​u​r​ ​p​r​e​m​i​u​m​ ​m​e​m​b​e​r​s​.
				 */
				answer: string
			}
			'9': {
				/**
				 * C​a​n​ ​I​ ​s​e​l​l​ ​m​y​ ​o​w​n​ ​p​r​o​d​u​c​t​s​?
				 */
				question: string
				/**
				 * Y​e​s​!​ ​Y​o​u​ ​c​a​n​ ​s​e​l​l​ ​y​o​u​r​ ​o​w​n​ ​p​r​o​d​u​c​t​s​.​ ​G​o​ ​t​o​ ​y​o​u​r​ ​p​r​o​f​i​l​e​,​ ​c​l​i​c​k​ ​o​n​ ​t​h​e​ ​'​P​r​o​d​u​c​t​'​ ​b​u​t​t​o​n​,​ ​a​n​d​ ​u​p​l​o​a​d​ ​y​o​u​r​ ​p​r​o​d​u​c​t​s​.​ ​Y​o​u​ ​c​a​n​ ​s​e​l​l​ ​e​x​c​l​u​s​i​v​e​ ​T​-​s​h​i​r​t​s​,​ ​m​a​s​k​s​,​ ​b​o​o​k​s​,​ ​p​o​s​t​e​r​s​,​ ​o​r​ ​a​n​y​ ​o​t​h​e​r​ ​t​y​p​e​ ​o​f​ ​p​r​o​d​u​c​t​.
				 */
				answer: string
			}
			'10': {
				/**
				 * H​o​w​ ​c​a​n​ ​I​ ​c​o​n​t​a​c​t​ ​'​হ​ব​ে​ ​ন​া​ক​ি​ ​C​o​f​f​e​e​'​?
				 */
				question: string
				/**
				 * I​f​ ​y​o​u​ ​w​a​n​t​ ​t​o​ ​c​o​n​t​a​c​t​ ​u​s​,​ ​v​i​s​i​t​ ​o​u​r​ ​c​o​n​t​a​c​t​ ​p​a​g​e​ ​a​n​d​ ​s​e​n​d​ ​y​o​u​r​ ​q​u​e​s​t​i​o​n​s​ ​o​r​ ​f​e​e​d​b​a​c​k​.​ ​W​e​ ​a​r​e​ ​a​l​w​a​y​s​ ​h​e​r​e​ ​f​o​r​ ​y​o​u​.​ ​O​u​r​ ​e​m​a​i​l​ ​a​d​d​r​e​s​s​ ​i​s​ ​'​s​u​p​p​o​r​t​@​h​o​b​e​n​a​k​i​c​o​f​f​e​e​.​c​o​m​'​.
				 */
				answer: string
			}
		}
	}
}

export type TranslationFunctions = {
	/**
	 * হবে নাকি Coffee?
	 */
	appName: () => LocalizedString
	/**
	 * Earn More from Your Fans without doing anything | হবে নাকি Coffee?
	 */
	title: () => LocalizedString
	/**
	 * হবে নাকি Coffee? is a platform where you can earn extra money from your fans and followers. Earn 30-40% more just by sharing a single link. Give your loyal supporters a chance to show their appreciation. From exclusive content and gifts to personal products and one-on-one support—everything is now possible from a single platform.
	 */
	description: () => LocalizedString
	/**
	 * hobe naki coffee,hobe naki,coffee,earn money,earn from fans,earn from followers,earn from supporters,earn from subscribers,earn from audience,earn from viewers,earn from readers,earn from listeners,earn from fans and followers,earn from fans and subscribers,earn from fans and audience,earn from fans and viewers,earn from fans and readers,earn from fans and listeners,earn from followers and subscribers,earn from followers and audience,earn from followers and viewers,earn from followers and readers,earn from followers and listeners,earn from subscribers and audience,earn from subscribers and viewers,earn from subscribers and readers,earn from subscribers and listeners,earn from audience and viewers,earn from audience and readers,earn from audience and listeners,earn from viewers and readers,earn from viewers and listeners,earn from readers and listeners
	 */
	keywords: () => LocalizedString
	/**
	 * @shamscorner
	 */
	appTwitterAccount: () => LocalizedString
	/**
	 * https://hobenakicoffee.com
	 */
	domain: () => LocalizedString
	/**
	 * mail@hobenakicoffee.com
	 */
	contactEmail: () => LocalizedString
	/**
	 * +1(817) 973-7285
	 */
	contactPhone: () => LocalizedString
	/**
	 * 7320, 1021 E Lincolnway, Cheyenne, WY, Laramie, US, 82001
	 */
	contactLocation: () => LocalizedString
	/**
	 * https://wa.me/13072212615
	 */
	contactWhatsapp: () => LocalizedString
	/**
	 * https://www.x.com/shamscorner-llc
	 */
	contactX: () => LocalizedString
	/**
	 * https://www.facebook.com/shamscorner.llc
	 */
	contactFacebook: () => LocalizedString
	/**
	 * https://www.youtube.com/channel/shamscorner-llc
	 */
	contactYoutube: () => LocalizedString
	common: {
		/**
		 * Upcoming
		 */
		upcoming: () => LocalizedString
	}
	appLogo: {
		/**
		 * হবে নাকি Coffee? is a platform where you can earn extra money from your fans and followers. Earn 30-40% more just by sharing a single link. Give your loyal supporters a chance to show their appreciation. From exclusive content and gifts to personal products and one-on-one support—everything is now possible from a single platform.
		 */
		hrefTitle: () => LocalizedString
		/**
		 * হবে নাকি Coffee? Logo
		 */
		alt: () => LocalizedString
	}
	landingPage: {
		title: {
			/**
			 * Creative Projects
			 */
			part1: () => LocalizedString
			/**
			 * Funding Made Easy
			 */
			part2: () => LocalizedString
			/**
			 * Why Wait Any Longer?
			 */
			part3: () => LocalizedString
		}
		/**
		 * Earn 30-40% more just by sharing a single link. Give your loyal supporters a chance to show their appreciation. From exclusive content and gifts to personal products and one-on-one support—everything is now possible from a single platform.
		 */
		subtitle: () => LocalizedString
		/**
		 * Liked by thousands of creators
		 */
		legend: () => LocalizedString
		callToAction: {
			/**
			 * Get Started
			 */
			getStarted: () => LocalizedString
			/**
			 * 100% Free
			 */
			itsFree: () => LocalizedString
			/**
			 * Do you want to be successful as a creator?
			 */
			title: () => LocalizedString
			/**
			 * Join thousands of creators who have already succeeded using "হবে নাকি Coffee?".
			 */
			subtitle: () => LocalizedString
			/**
			 * Coming soon! Keep an eye on our Facebook page. We will inform you as soon as it is released.
			 */
			inComingMessage: () => LocalizedString
			tickItem: {
				/**
				 * Unlimited gift receiving opportunity
				 */
				'0': () => LocalizedString
				/**
				 * Privacy Focused and Secure Platform
				 */
				'1': () => LocalizedString
				/**
				 * Very easy to use
				 */
				'2': () => LocalizedString
				/**
				 * Always ready for any help
				 */
				'3': () => LocalizedString
				/**
				 * Customize as you like
				 */
				'4': () => LocalizedString
			}
		}
		heroProps: {
			'0': {
				/**
				 * Attractive Gifts
				 */
				title: () => LocalizedString
				/**
				 * Unlock the opportunity to receive unlimited gifts from your loyal supporters.
				 */
				subtitle: () => LocalizedString
				/**
				 * <rect x="3" y="8" width="18" height="4" rx="1"/><path d="M12 8v13"/><path d="M19 12v7a2 2 0 0 1-2 2H7a2 2 0 0 1-2-2v-7"/><path d="M7.5 8a2.5 2.5 0 0 1 0-5A4.8 8 0 0 1 12 8a4.8 8 0 0 1 4.5-5 2.5 2.5 0 0 1 0 5"/>
				 */
				icon: () => LocalizedString
				/**
				 * bg-pink-50 border-pink-200 text-pink-500
				 */
				extraClass: () => LocalizedString
			}
			'1': {
				/**
				 * Exclusive Content
				 */
				title: () => LocalizedString
				/**
				 * Create and sell premium exclusive content to boost your income.
				 */
				subtitle: () => LocalizedString
				/**
				 * <path d="M20.38 3.46 16 2a4 4 0 0 1-8 0L3.62 3.46a2 2 0 0 0-1.34 2.23l.58 3.47a1 1 0 0 0 .99.84H6v10c0 1.1.9 2 2 2h8a2 2 0 0 0 2-2V10h2.15a1 1 0 0 0 .99-.84l.58-3.47a2 2 0 0 0-1.34-2.23z"/>
				 */
				icon: () => LocalizedString
				/**
				 * bg-blue-50 border-blue-200 text-blue-500
				 */
				extraClass: () => LocalizedString
			}
			'2': {
				/**
				 * Self Products
				 */
				title: () => LocalizedString
				/**
				 * Set up your own online store and sell your unique products effortlessly.
				 */
				subtitle: () => LocalizedString
				/**
				 * <path d="M6 2 3 6v14a2 2 0 0 0 2 2h14a2 2 0 0 0 2-2V6l-3-4Z"/><path d="M3 6h18"/><path d="M16 10a4 4 0 0 1-8 0"/>
				 */
				icon: () => LocalizedString
				/**
				 * bg-amber-50 border-amber-300 text-amber-600
				 */
				extraClass: () => LocalizedString
			}
			'3': {
				/**
				 * User Membership
				 */
				title: () => LocalizedString
				/**
				 * Offer premium one-on-one membership services to your dedicated audience.
				 */
				subtitle: () => LocalizedString
				/**
				 * <path d="M16 21v-2a4 4 0 0 0-4-4H6a4 4 0 0 0-4 4v2"/><circle cx="9" cy="7" r="4"/><path d="M22 21v-2a4 4 0 0 0-3-3.87"/><path d="M16 3.13a4 4 0 0 1 0 7.75"/>
				 */
				icon: () => LocalizedString
				/**
				 * bg-emerald-50 border-emerald-200 text-emerald-500
				 */
				extraClass: () => LocalizedString
			}
		}
		howItIsBeingUsed: {
			/**
			 * The success story of Abdur Rahman
			 */
			title: () => LocalizedString
			/**
			 * See how Abdur Rahman is using "হবে নাকি Coffee?" to his advantage, even as a small content creator.
			 */
			subtitle: () => LocalizedString
			facebook: {
				/**
				 * See how Abdur Rahman is using Facebook posts to his advantage
				 */
				hint: () => LocalizedString
			}
			youtube: {
				/**
				 * See how Abdur Rahman is using YouTube videos to his advantage
				 */
				hint: () => LocalizedString
			}
			/**
			 * Even in short-form videos, Abdur Rahman is earning using "হবে নাকি Coffee?".
			 */
			shortFormVideo: () => LocalizedString
			/**
			 * Abdur Rahman has also used the link of "হবে নাকি Coffee?" in his social media profile.
			 */
			socialMediaProfile: () => LocalizedString
			/**
			 * You can use it in the same way on your blog, podcast, website, or any other platform.
			 */
			outro: () => LocalizedString
		}
		customizedUserProfile: {
			/**
			 * Now let’s take a look at your customized profile at a glance.
			 */
			title: () => LocalizedString
			/**
			 * Customize your profile page as you like. Here is an example of Abdur Rahman’s profile page. But you can customize your profile page according to the type of work you do.
			 */
			subtitle: () => LocalizedString
			/**
			 * This profile is shown as an example. Your profile is entirely yours. You can customize it as you like.
			 */
			disclaimer: () => LocalizedString
		}
		designedForCreators: {
			/**
			 * Now You Are Not Alone.
			 */
			title: () => LocalizedString
			/**
			 * A simple platform to connect with your loyal supporters. Collect the necessary funds for your work directly from your supporters in a simple, fast, and reliable way.
			 */
			subTitle: () => LocalizedString
			features: {
				'0': {
					/**
					 * Easy & Direct Connection
					 */
					title: () => LocalizedString
					/**
					 * Your supporters will reach out to you first.
					 */
					description: () => LocalizedString
					/**
					 * <path d="M16 21v-2a4 4 0 0 0-4-4H6a4 4 0 0 0-4 4v2"/><circle cx="9" cy="7" r="4"/><path d="M22 21v-2a4 4 0 0 0-3-3.87"/><path d="M16 3.13a4 4 0 0 1 0 7.75"/>
					 */
					icon: () => LocalizedString
					/**
					 * text-[#9f8bbc]
					 */
					color: () => LocalizedString
				}
				'1': {
					/**
					 * Fast & Hassle-Free
					 */
					title: () => LocalizedString
					/**
					 * Collect funds quickly without delays or intermediaries.
					 */
					description: () => LocalizedString
					/**
					 * <circle cx="12" cy="12" r="10"/><path d="M8 14s1.5 2 4 2 4-2 4-2"/><line x1="9" x2="9.01" y1="9" y2="9"/><line x1="15" x2="15.01" y1="9" y2="9"/>
					 */
					icon: () => LocalizedString
					/**
					 * text-[#80b6ab]
					 */
					color: () => LocalizedString
				}
				'2': {
					/**
					 * 100% Ownership
					 */
					title: () => LocalizedString
					/**
					 * You have full control over your supporters’ list and connections.
					 */
					description: () => LocalizedString
					/**
					 * <path d="M11.562 3.266a.5.5 0 0 1 .876 0L15.39 8.87a1 1 0 0 0 1.516.294L21.183 5.5a.5.5 0 0 1 .798.519l-2.834 10.246a1 1 0 0 1-.956.734H5.81a1 1 0 0 1-.957-.734L2.02 6.02a.5.5 0 0 1 .798-.519l4.276 3.664a1 1 0 0 0 1.516-.294z"/><path d="M5 21h14"/>
					 */
					icon: () => LocalizedString
					/**
					 * text-[#e4796a]
					 */
					color: () => LocalizedString
				}
				'3': {
					/**
					 * Reliable Platform
					 */
					title: () => LocalizedString
					/**
					 * Secure and transparent transactions for worry-free funding.
					 */
					description: () => LocalizedString
					/**
					 * <path d="m16 16 3-8 3 8c-.87.65-1.92 1-3 1s-2.13-.35-3-1Z"/><path d="m2 16 3-8 3 8c-.87.65-1.92 1-3 1s-2.13-.35-3-1Z"/><path d="M7 21h10"/><path d="M12 3v18"/><path d="M3 7h2c2 0 5-1 7-2 2 1 5 2 7 2h2"/>
					 */
					icon: () => LocalizedString
					/**
					 * text-[#f6c64f]
					 */
					color: () => LocalizedString
				}
				'4': {
					/**
					 * Built for Creators
					 */
					title: () => LocalizedString
					/**
					 * Designed specifically to make funding easy for you.
					 */
					description: () => LocalizedString
					/**
					 * <path d="M19 14c1.49-1.46 3-3.21 3-5.5A5.5 5.5 0 0 0 16.5 3c-1.76 0-3 .5-4.5 2-1.5-1.5-2.74-2-4.5-2A5.5 5.5 0 0 0 2 8.5c0 2.3 1.5 4.05 3 5.5l7 7Z"/><path d="M12 5 9.04 7.96a2.17 2.17 0 0 0 0 3.08c.82.82 2.13.85 3 .07l2.07-1.9a2.82 2.82 0 0 1 3.79 0l2.96 2.66"/><path d="m18 15-2-2"/><path d="m15 18-2-2"/>
					 */
					icon: () => LocalizedString
					/**
					 * text-[#e29aaf]
					 */
					color: () => LocalizedString
				}
			}
		}
	}
	pageContact: {
		/**
		 * Contact Us
		 */
		title: () => LocalizedString
		/**
		 * If you have any questions or would like to contact us, please fill out the form below or email us directly.
		 */
		description: () => LocalizedString
		/**
		 * contact, contact us, হবে নাকি Coffee?
		 */
		keywords: () => LocalizedString
		contactForm: {
			/**
			 * Full Name
			 */
			fullName: () => LocalizedString
			/**
			 * Abdur Rahman
			 */
			fullNamePlaceholder: () => LocalizedString
			/**
			 * Email
			 */
			email: () => LocalizedString
			/**
			 * abdur-rahman@gmail.com
			 */
			emailPlaceholder: () => LocalizedString
			/**
			 * Subject
			 */
			subject: () => LocalizedString
			/**
			 * About account activation
			 */
			subjectPlaceholder: () => LocalizedString
			/**
			 * Message
			 */
			message: () => LocalizedString
			/**
			 * Hello, I have a question about my account...
			 */
			messagePlaceholder: () => LocalizedString
			/**
			 * Send
			 */
			send: () => LocalizedString
			/**
			 * By using this form, you agree to our privacy policy.
			 */
			privacyHint: () => LocalizedString
		}
		/**
		 * We believe that every creator has a unique talent worth sharing with the world. We respect your talent, value your achievements, and help you succeed.
		 */
		ourMoto: () => LocalizedString
	}
	pagePrivacyPolicy: {
		/**
		 * Privacy Policy
		 */
		title: () => LocalizedString
		/**
		 * This privacy policy will help you understand how হবে নাকি Coffee? uses and protects the data you provide to us when you visit and use হবে নাকি Coffee?.
		 */
		description: () => LocalizedString
		/**
		 * privacy policy, হবে নাকি Coffee?
		 */
		keywords: () => LocalizedString
	}
	pageTermsAndConditions: {
		/**
		 * Terms and Conditions
		 */
		title: () => LocalizedString
		/**
		 * This document outlines the terms and conditions for using হবে নাকি Coffee?.
		 */
		description: () => LocalizedString
		/**
		 * terms, conditions, হবে নাকি Coffee?
		 */
		keywords: () => LocalizedString
	}
	page404: {
		/**
		 * Page not found!
		 */
		title: () => LocalizedString
		/**
		 * Sorry, we couldn’t find the page you’re looking for.
		 */
		description: () => LocalizedString
		actions: {
			goHome: {
				/**
				 * Go back home
				 */
				label: () => LocalizedString
				/**
				 * /
				 */
				href: () => LocalizedString
			}
			contactSupport: {
				/**
				 * Contact support
				 */
				label: () => LocalizedString
				/**
				 * /contact
				 */
				href: () => LocalizedString
			}
		}
	}
	navbar: {
		items: {
			'0': {
				/**
				 * How it works?
				 */
				name: () => LocalizedString
				/**
				 * /#how-it-works
				 */
				link: () => LocalizedString
			}
			'1': {
				/**
				 * FAQs
				 */
				name: () => LocalizedString
				/**
				 * /faqs
				 */
				link: () => LocalizedString
			}
			'2': {
				/**
				 * Contact
				 */
				name: () => LocalizedString
				/**
				 * /contact
				 */
				link: () => LocalizedString
			}
		}
		/**
		 * Sign up
		 */
		signup: () => LocalizedString
		/**
		 * Log in
		 */
		login: () => LocalizedString
		srOnly: {
			/**
			 * Main navigation
			 */
			header: () => LocalizedString
			/**
			 * Open main menu
			 */
			openMenu: () => LocalizedString
			/**
			 * Close main menu
			 */
			closeMenu: () => LocalizedString
		}
	}
	footer: {
		/**
		 * © 2024 - 2025 হবে নাকি Coffee? all rights reserved
		 */
		copyrights: () => LocalizedString
		links: {
			'0': {
				/**
				 * About
				 */
				name: () => LocalizedString
				/**
				 * /about
				 */
				link: () => LocalizedString
			}
			'1': {
				/**
				 * Support
				 */
				name: () => LocalizedString
				/**
				 * /support
				 */
				link: () => LocalizedString
			}
			'2': {
				/**
				 * Terms of Service
				 */
				name: () => LocalizedString
				/**
				 * /terms
				 */
				link: () => LocalizedString
			}
			'3': {
				/**
				 * Privacy Policy
				 */
				name: () => LocalizedString
				/**
				 * /privacy
				 */
				link: () => LocalizedString
			}
		}
	}
	pageFaqs: {
		/**
		 * Frequently Asked Questions (FAQs)
		 */
		title: () => LocalizedString
		/**
		 * Some commonly asked questions (FAQs) about হবে নাকি Coffee?.
		 */
		description: () => LocalizedString
		/**
		 * faqs,questions,what is hobe naki coffee, হবে নাকি Coffee?
		 */
		keywords: () => LocalizedString
		items: {
			'0': {
				/**
				 * What is 'হবে নাকি Coffee'?
				 */
				question: () => LocalizedString
				/**
				 * 'হবে নাকি Coffee' is a platform where creators (such as writers, artists, content creators) can request their supporters to buy them a coffee. It’s a symbolic way for users to financially support their favorite creators. Earn 30-40% more just by sharing a single link. From exclusive content and gifts to personal products and one-on-one support—everything is now possible from a single platform.
				 */
				answer: () => LocalizedString
			}
			'1': {
				/**
				 * Who is 'হবে নাকি Coffee' for?
				 */
				question: () => LocalizedString
				/**
				 * Anyone can use this platform, especially YouTubers, bloggers, artists, singers, freelancers, teachers, and any type of content creator who wants financial support from their supporters.
				 */
				answer: () => LocalizedString
			}
			'2': {
				/**
				 * How can I withdraw money?
				 */
				question: () => LocalizedString
				/**
				 * Go to your profile and click on the 'Payouts' page. Select the withdrawal amount and method (bKash/Nagad/Bank) and click on 'Withdraw'. You will receive the money within 24-48 hours (depending on business days). It's that simple!
				 */
				answer: () => LocalizedString
			}
			'3': {
				/**
				 * How can my supporters send me money?
				 */
				question: () => LocalizedString
				/**
				 * Your supporters can visit your profile, choose the number of coffees they want to buy, and click on the 'Support $$' button to send money. It's a very simple process. A payment form will appear where they can complete the transaction. We support all payment options (bKash/Nagad/Bank, etc.).
				 */
				answer: () => LocalizedString
			}
			'4': {
				/**
				 * How do I create an account?
				 */
				question: () => LocalizedString
				/**
				 * Go to the homepage of the website and click on the 'Sign Up' button. Complete the registration using email, phone number, or social media accounts (Google, Facebook). Set up your profile and start posting coffee requests!
				 */
				answer: () => LocalizedString
			}
			'5': {
				/**
				 * Does 'হবে নাকি Coffee' charge any fees?
				 */
				question: () => LocalizedString
				/**
				 * We do not charge a monthly fee. It’s completely free, and you can use it as long as you like. Publishing and emails are free for everyone. We only charge a 5% transaction fee, and creators keep 95% of their earnings. We make money only when you do. We never show ads or sell your data. You have complete control over your data.
				 */
				answer: () => LocalizedString
			}
			'6': {
				/**
				 * Is 'হবে নাকি Coffee' safe to use?
				 */
				question: () => LocalizedString
				/**
				 * We secure all transactions with SSL encryption. We do not store any personal information (such as card details). We do not show ads or sell your data. You have complete control over your data. Our support team is always available to assist you with any issues.
				 */
				answer: () => LocalizedString
			}
			'7': {
				/**
				 * Do my supporters have to pay any fees?
				 */
				question: () => LocalizedString
				/**
				 * No. Your supporters are not required to pay any fees. If they wish to support their favorite creator, they can contribute an amount equivalent to a coffee. No extra charges are taken from them.
				 */
				answer: () => LocalizedString
			}
			'8': {
				/**
				 * Can I directly communicate with my supporters?
				 */
				question: () => LocalizedString
				/**
				 * Yes! You can directly communicate with your supporters. You can visit their profile and send messages. You can offer exclusive content, gifts, or any other type of support to your premium members.
				 */
				answer: () => LocalizedString
			}
			'9': {
				/**
				 * Can I sell my own products?
				 */
				question: () => LocalizedString
				/**
				 * Yes! You can sell your own products. Go to your profile, click on the 'Product' button, and upload your products. You can sell exclusive T-shirts, masks, books, posters, or any other type of product.
				 */
				answer: () => LocalizedString
			}
			'10': {
				/**
				 * How can I contact 'হবে নাকি Coffee'?
				 */
				question: () => LocalizedString
				/**
				 * If you want to contact us, visit our contact page and send your questions or feedback. We are always here for you. Our email address is 'support@hobenakicoffee.com'.
				 */
				answer: () => LocalizedString
			}
		}
	}
}

export type Formatters = {}
